# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Mon Feb 10 21:08:55 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1223, 689)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Vertical)
        self.mainSplitter.setOpaqueResize(True)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName("mainSplitter")
        self.mainSplitterTopWidget = QtWidgets.QWidget(self.mainSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mainSplitterTopWidget.sizePolicy().hasHeightForWidth())
        self.mainSplitterTopWidget.setSizePolicy(sizePolicy)
        self.mainSplitterTopWidget.setObjectName("mainSplitterTopWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainSplitterTopWidget)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.proteinsTitleLabel = QtWidgets.QLabel(self.mainSplitterTopWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proteinsTitleLabel.sizePolicy().hasHeightForWidth())
        self.proteinsTitleLabel.setSizePolicy(sizePolicy)
        self.proteinsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.proteinsTitleLabel.setObjectName("proteinsTitleLabel")
        self.verticalLayout_2.addWidget(self.proteinsTitleLabel)
        self.proteinsSearchWidget = QtWidgets.QWidget(self.mainSplitterTopWidget)
        self.proteinsSearchWidget.setObjectName("proteinsSearchWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.proteinsSearchWidget)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.proteinsSearchLineEdit = QtWidgets.QLineEdit(self.proteinsSearchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proteinsSearchLineEdit.sizePolicy().hasHeightForWidth())
        self.proteinsSearchLineEdit.setSizePolicy(sizePolicy)
        self.proteinsSearchLineEdit.setPlaceholderText("")
        self.proteinsSearchLineEdit.setClearButtonEnabled(True)
        self.proteinsSearchLineEdit.setObjectName("proteinsSearchLineEdit")
        self.horizontalLayout_5.addWidget(self.proteinsSearchLineEdit)
        self.proteinsSearchTypeComboBox = QtWidgets.QComboBox(self.proteinsSearchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proteinsSearchTypeComboBox.sizePolicy().hasHeightForWidth())
        self.proteinsSearchTypeComboBox.setSizePolicy(sizePolicy)
        self.proteinsSearchTypeComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.proteinsSearchTypeComboBox.setObjectName("proteinsSearchTypeComboBox")
        self.proteinsSearchTypeComboBox.addItem("")
        self.proteinsSearchTypeComboBox.addItem("")
        self.proteinsSearchTypeComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.proteinsSearchTypeComboBox)
        self.proteinsSearchPushButton = QtWidgets.QPushButton(self.proteinsSearchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proteinsSearchPushButton.sizePolicy().hasHeightForWidth())
        self.proteinsSearchPushButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pixmap/icons/16x16/edit-find-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.proteinsSearchPushButton.setIcon(icon)
        self.proteinsSearchPushButton.setIconSize(QtCore.QSize(16, 16))
        self.proteinsSearchPushButton.setCheckable(False)
        self.proteinsSearchPushButton.setObjectName("proteinsSearchPushButton")
        self.horizontalLayout_5.addWidget(self.proteinsSearchPushButton)
        self.verticalLayout_2.addWidget(self.proteinsSearchWidget)
        self.proteinsTableWidget = TableWidget(self.mainSplitterTopWidget)
        self.proteinsTableWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.proteinsTableWidget.setStyleSheet(
            "QTableView:!active  {selection-color: palette(Highlighted-Text); selection-background-color: palette(Highlight);}")
        self.proteinsTableWidget.setAutoScroll(False)
        self.proteinsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.proteinsTableWidget.setAlternatingRowColors(True)
        self.proteinsTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.proteinsTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.proteinsTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.proteinsTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.proteinsTableWidget.setShowGrid(False)
        self.proteinsTableWidget.setWordWrap(False)
        self.proteinsTableWidget.setCornerButtonEnabled(False)
        self.proteinsTableWidget.setColumnCount(2)
        self.proteinsTableWidget.setObjectName("proteinsTableWidget")
        self.proteinsTableWidget.setColumnCount(2)
        self.proteinsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.proteinsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.proteinsTableWidget.setHorizontalHeaderItem(1, item)
        self.proteinsTableWidget.horizontalHeader().setStretchLastSection(False)
        self.proteinsTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.proteinsTableWidget)
        self.mainSplitterBottomWidget = QtWidgets.QWidget(self.mainSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSplitterBottomWidget.sizePolicy().hasHeightForWidth())
        self.mainSplitterBottomWidget.setSizePolicy(sizePolicy)
        self.mainSplitterBottomWidget.setObjectName("mainSplitterBottomWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainSplitterBottomWidget)
        self.verticalLayout_3.setContentsMargins(0, 6, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.mainSplitterBottomWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.subSplitterLeftWidget = QtWidgets.QWidget(self.splitter)
        self.subSplitterLeftWidget.setObjectName("subSplitterLeftWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.subSplitterLeftWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.peptideTitleLabel = QtWidgets.QLabel(self.subSplitterLeftWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peptideTitleLabel.sizePolicy().hasHeightForWidth())
        self.peptideTitleLabel.setSizePolicy(sizePolicy)
        self.peptideTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.peptideTitleLabel.setObjectName("peptideTitleLabel")
        self.verticalLayout.addWidget(self.peptideTitleLabel)
        self.peptidesTableWidget = TableWidget(self.subSplitterLeftWidget)
        self.peptidesTableWidget.setStyleSheet(
            "QTableView:!active  {selection-color: palette(Highlighted-Text); selection-background-color: palette(Highlight);}")
        self.peptidesTableWidget.setAutoScroll(False)
        self.peptidesTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.peptidesTableWidget.setAlternatingRowColors(True)
        self.peptidesTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.peptidesTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.peptidesTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.peptidesTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.peptidesTableWidget.setShowGrid(False)
        self.peptidesTableWidget.setWordWrap(False)
        self.peptidesTableWidget.setCornerButtonEnabled(False)
        self.peptidesTableWidget.setObjectName("peptidesTableWidget")
        self.peptidesTableWidget.setColumnCount(4)
        self.peptidesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.peptidesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peptidesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peptidesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peptidesTableWidget.setHorizontalHeaderItem(3, item)
        self.peptidesTableWidget.horizontalHeader().setStretchLastSection(False)
        self.peptidesTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.peptidesTableWidget)
        self.subSplitterRightWidget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subSplitterRightWidget.sizePolicy().hasHeightForWidth())
        self.subSplitterRightWidget.setSizePolicy(sizePolicy)
        self.subSplitterRightWidget.setObjectName("subSplitterRightWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.subSplitterRightWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.subProteinsTitleLabel = QtWidgets.QLabel(self.subSplitterRightWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subProteinsTitleLabel.sizePolicy().hasHeightForWidth())
        self.subProteinsTitleLabel.setSizePolicy(sizePolicy)
        self.subProteinsTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subProteinsTitleLabel.setObjectName("subProteinsTitleLabel")
        self.verticalLayout_5.addWidget(self.subProteinsTitleLabel)
        self.subProteinsTableWidget = TableWidget(self.subSplitterRightWidget)
        self.subProteinsTableWidget.setStyleSheet(
            "QTableView:!active  {selection-color: palette(Highlighted-Text); selection-background-color: palette(Highlight);}")
        self.subProteinsTableWidget.setAutoScroll(False)
        self.subProteinsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.subProteinsTableWidget.setAlternatingRowColors(True)
        self.subProteinsTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.subProteinsTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.subProteinsTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.subProteinsTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.subProteinsTableWidget.setShowGrid(False)
        self.subProteinsTableWidget.setWordWrap(False)
        self.subProteinsTableWidget.setCornerButtonEnabled(False)
        self.subProteinsTableWidget.setObjectName("subProteinsTableWidget")
        self.subProteinsTableWidget.setColumnCount(2)
        self.subProteinsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.subProteinsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.subProteinsTableWidget.setHorizontalHeaderItem(1, item)
        self.subProteinsTableWidget.horizontalHeader().setStretchLastSection(False)
        self.subProteinsTableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.subProteinsTableWidget)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout_6.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1223, 29))
        self.menuBar.setObjectName("menuBar")
        self.fileMenu = QtWidgets.QMenu(self.menuBar)
        self.fileMenu.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.fileMenu.setObjectName("fileMenu")
        self.databaseMenu = QtWidgets.QMenu(self.menuBar)
        self.databaseMenu.setObjectName("databaseMenu")
        self.workingDigestionMenu = QtWidgets.QMenu(self.menuBar)
        self.workingDigestionMenu.setObjectName("workingDigestionMenu")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.createDatabaseAction = QtWidgets.QAction(MainWindow)
        self.createDatabaseAction.setObjectName("createDatabaseAction")
        self.openDatabaseAction = QtWidgets.QAction(MainWindow)
        self.openDatabaseAction.setObjectName("openDatabaseAction")
        self.importFastaAction = QtWidgets.QAction(MainWindow)
        self.importFastaAction.setObjectName("importFastaAction")
        self.quitAction = QtWidgets.QAction(MainWindow)
        self.quitAction.setObjectName("quitAction")
        self.manageDigestionAction = QtWidgets.QAction(MainWindow)
        self.manageDigestionAction.setObjectName("manageDigestionAction")
        self.removeDigestionAction = QtWidgets.QAction(MainWindow)
        self.removeDigestionAction.setObjectName("removeDigestionAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.fileMenu.addAction(self.createDatabaseAction)
        self.fileMenu.addAction(self.openDatabaseAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.quitAction)
        self.databaseMenu.addAction(self.importFastaAction)
        self.databaseMenu.addAction(self.manageDigestionAction)
        self.menuHelp.addAction(self.aboutAction)
        self.menuBar.addAction(self.fileMenu.menuAction())
        self.menuBar.addAction(self.databaseMenu.menuAction())
        self.menuBar.addAction(self.workingDigestionMenu.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.createDatabaseAction, QtCore.SIGNAL("triggered()"), MainWindow.createDatabaseActionTriggered)
        QtCore.QObject.connect(self.openDatabaseAction, QtCore.SIGNAL("triggered()"), MainWindow.openDatabaseActionTriggered)
        QtCore.QObject.connect(self.importFastaAction, QtCore.SIGNAL("triggered()"), MainWindow.importFastaActionTriggered)
        QtCore.QObject.connect(self.proteinsSearchPushButton, QtCore.SIGNAL("clicked()"), MainWindow.proteinsSearchPushButtonClicked)
        QtCore.QObject.connect(self.proteinsSearchLineEdit, QtCore.SIGNAL("returnPressed()"), self.proteinsSearchPushButton.click)
        QtCore.QObject.connect(self.manageDigestionAction, QtCore.SIGNAL("triggered()"), MainWindow.manageDigestionActionTriggered)
        QtCore.QObject.connect(self.proteinsTableWidget, QtCore.SIGNAL("itemSelectionChanged()"), MainWindow.proteinsTableWidgetItemSelectionChanged)
        QtCore.QObject.connect(self.peptidesTableWidget, QtCore.SIGNAL("itemSelectionChanged()"), MainWindow.peptidesTableWidgetItemSelectionChanged)
        QtCore.QObject.connect(self.aboutAction, QtCore.SIGNAL("triggered()"), MainWindow.aboutActionTriggered)
        QtCore.QObject.connect(self.proteinsSearchLineEdit, QtCore.SIGNAL("textChanged(QString)"), MainWindow.proteinsSearchLineEditTextChanged)
        QtCore.QObject.connect(self.proteinsTableWidget, QtCore.SIGNAL("itemDoubleClicked(QTableWidgetItem*)"), MainWindow.refreshPeptidesTableWidget)
        QtCore.QObject.connect(self.peptidesTableWidget, QtCore.SIGNAL("itemDoubleClicked(QTableWidgetItem*)"), MainWindow.refreshSubProteinsTableWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "ProteinDigester", None, -1))
        self.proteinsTitleLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Proteins</span></p></body></html>", None, -1))
        self.proteinsSearchTypeComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "By name", None, -1))
        self.proteinsSearchTypeComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "By sequence", None, -1))
        self.proteinsSearchTypeComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "By digest peptide", None, -1))
        self.proteinsTableWidget.setSortingEnabled(True)
        self.proteinsTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "#", None, -1))
        self.proteinsTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.peptideTitleLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Peptides from selected protein</span></p></body></html>", None, -1))
        self.peptidesTableWidget.setSortingEnabled(True)
        self.peptidesTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "#", None, -1))
        self.peptidesTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Sequence", None, -1))
        self.peptidesTableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Missed cleavages", None, -1))
        self.peptidesTableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Unique", None, -1))
        self.subProteinsTitleLabel.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Proteins from selected peptide</span></p></body></html>", None, -1))
        self.subProteinsTableWidget.setSortingEnabled(True)
        self.subProteinsTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "#", None, -1))
        self.subProteinsTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Name", None, -1))
        self.fileMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.databaseMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Digestion database", None, -1))
        self.workingDigestionMenu.setTitle(QtWidgets.QApplication.translate("MainWindow", "Working digestion", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.createDatabaseAction.setText(QtWidgets.QApplication.translate("MainWindow", "Create digestion database", None, -1))
        self.createDatabaseAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.openDatabaseAction.setText(QtWidgets.QApplication.translate("MainWindow", "Open digestion database", None, -1))
        self.openDatabaseAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.importFastaAction.setText(QtWidgets.QApplication.translate("MainWindow", "Import FASTA file", None, -1))
        self.importFastaAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I", None, -1))
        self.quitAction.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.manageDigestionAction.setText(QtWidgets.QApplication.translate("MainWindow", "Manage digestion", None, -1))
        self.manageDigestionAction.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+M", None, -1))
        self.removeDigestionAction.setText(QtWidgets.QApplication.translate("MainWindow", "Remove digestion", None, -1))
        self.aboutAction.setText(QtWidgets.QApplication.translate("MainWindow", "About ProteinDigester", None, -1))

from ui.widgets.tablewidget import TableWidget
